#!/usr/bin/env python3
"""
lecture03_demos.py — Demos for Lecture 03 (Chapter 8 + Informatics linkages)

- Decision Context → Informatics Role → Code → Output → Interpretation → Decision Impact

Run (local):
  python lecture03_demos.py --out_dir artifacts --show_plots 0

Run (Colab/Azure):
  !python lecture03_demos.py --out_dir artifacts --show_plots 0

Outputs:
  artifacts/
    demo01_validation_report.csv
    demo01_validation_summary.json
    demo02_missingness_summary.json
    demo02_imputation_plot.png
    demo03_synthetic_dataset.csv
    demo03_model_metrics.json
    demo03_confusion_matrix.png
    demo03_feature_importance.png
    
"""

from __future__ import annotations

import argparse
import json
import math
import os
import sys
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Tuple, Optional

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Optional dependency: pandera (validation). If unavailable, we degrade gracefully.
try:
    import pandera as pa
    from pandera import Column, DataFrameSchema, Check
    PANDERA_AVAILABLE = True
except Exception:
    PANDERA_AVAILABLE = False

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
)
from sklearn.linear_model import LogisticRegression


# ---------------------------
# Utilities: explainability scaffolding
# ---------------------------

@dataclass
class DecisionBox:
    who_decides: str
    decision: str
    risk_if_wrong: str
    how_this_demo_helps: str

@dataclass
class DemoNarrative:
    title: str
    decision_context: str
    informatics_role: str
    interpretation: str
    decision_impact: str
    artifacts: List[str]

class Narrator:
    """Prints structured, readable demo narration and builds a markdown narrative file."""
    def __init__(self, out_dir: Path):
        self.out_dir = out_dir
        self.md_lines: List[str] = []
        self._init_md()

    def _init_md(self):
        self.md_lines.append("# Lecture 03 Demos — Explainable Outputs\n")
        self.md_lines.append(f"_Generated: {datetime.now().isoformat(timespec='seconds')}_\n")
        self.md_lines.append(
            "This page is auto-generated by `lecture03_demos.py` and is designed to map cleanly to the lecture.\n"
            "Each demo follows the same structure: **Decision Context → Informatics Role → Output → Interpretation → Decision Impact**.\n"
        )

    def section(self, h2: str):
        print("\n" + "=" * 88)
        print(h2)
        print("=" * 88)
        self.md_lines.append(f"\n## {h2}\n")

    def decision_box(self, box: DecisionBox):
        # Console
        print("\n[Decision Box]")
        print(f"- Who decides: {box.who_decides}")
        print(f"- Decision: {box.decision}")
        print(f"- Risk if wrong: {box.risk_if_wrong}")
        print(f"- How this demo helps: {box.how_this_demo_helps}")

        # Markdown
        self.md_lines.append(
            "\n> **Decision Box**\n"
            f">\n> **Who decides:** {box.who_decides}  \n"
            f"> **Decision:** {box.decision}  \n"
            f"> **Risk if wrong:** {box.risk_if_wrong}  \n"
            f"> **How this demo helps:** {box.how_this_demo_helps}\n"
        )

    def text_block(self, label: str, text: str):
        # Console
        print(f"\n{label}:\n{text.strip()}")
        # Markdown
        self.md_lines.append(f"\n### {label}\n\n{text.strip()}\n")

    def artifacts(self, artifact_paths: List[Path]):
        if not artifact_paths:
            return
        self.md_lines.append("\n### Artifacts\n")
        for p in artifact_paths:
            rel = p.name
            # Render images inline; others as links
            if p.suffix.lower() in [".png", ".jpg", ".jpeg", ".svg", ".webp"]:
                self.md_lines.append(f"- `{rel}`\n\n  ![]({rel})\n")
            else:
                self.md_lines.append(f"- [{rel}]({rel})\n")

    def finalize(self) -> Path:
        md_path = self.out_dir / "lecture03_demo_narrative.md"
        md_path.write_text("\n".join(self.md_lines), encoding="utf-8")
        return md_path


def safe_mkdir(p: Path):
    p.mkdir(parents=True, exist_ok=True)


def write_json(path: Path, obj: dict):
    path.write_text(json.dumps(obj, indent=2, sort_keys=True), encoding="utf-8")


def seed_everything(seed: int = 42):
    np.random.seed(seed)


# ---------------------------
# Demo 0: Synthetic data generator (shared for all)
# ---------------------------

def generate_telemetry_dataset(n: int = 2500, missing_rate: float = 0.08, seed: int = 42) -> pd.DataFrame:
    """
    Generates a realistic-enough telemetry dataset for teaching:
      - sensor_temp_c: operating temperature
      - vibration_mm_s: vibration velocity
      - voltage_v: supply voltage
      - pressure_kpa: hydraulic pressure
      - load_pct: system load (0-100)
      - time_min: time index
      - failure_within_24h: label (binary)
    Includes:
      - mild drift
      - correlated signals
      - injected missingness
      - injected outliers (for validation demo)
    """
    seed_everything(seed)
    time_min = np.arange(n)

    # Load pattern: daily-ish sinusoid + noise, bounded
    load = 55 + 25*np.sin(2*np.pi*time_min/480) + np.random.normal(0, 8, n)
    load = np.clip(load, 0, 100)

    # Temperature: correlated with load + drift
    drift = 0.003 * time_min
    temp = 45 + 0.35*load + drift + np.random.normal(0, 2.2, n)

    # Vibration: increases with load; spikes when temp high
    vib = 1.2 + 0.03*load + 0.02*np.maximum(temp - 75, 0) + np.random.normal(0, 0.25, n)
    vib = np.clip(vib, 0, None)

    # Voltage: nominal ~ 48V with small variation; droops slightly under high load
    voltage = 48 - 0.015*load + np.random.normal(0, 0.35, n)

    # Pressure: depends on load + noise
    pressure = 210 + 0.8*load + np.random.normal(0, 7.0, n)

    # Failure probability: nonlinear combination (teaching-friendly)
    # High risk when vib high, temp high, voltage low (droop), pressure high (overload)
    risk_score = (
        0.06*(temp - 70)
        + 1.1*(vib - 2.2)
        - 0.9*(voltage - 47.2)
        + 0.01*(pressure - 260)
    )
    # squash
    prob = 1 / (1 + np.exp(-risk_score))
    # Add base rarity control
    prob = np.clip(0.02 + 0.35*prob, 0, 0.95)
    y = (np.random.rand(n) < prob).astype(int)

    df = pd.DataFrame({
        "time_min": time_min,
        "load_pct": load,
        "sensor_temp_c": temp,
        "vibration_mm_s": vib,
        "voltage_v": voltage,
        "pressure_kpa": pressure,
        "failure_within_24h": y,
    })

    # Inject missingness at random columns (except label/time)
    rng = np.random.default_rng(seed + 1)
    cols = ["load_pct", "sensor_temp_c", "vibration_mm_s", "voltage_v", "pressure_kpa"]
    for c in cols:
        mask = rng.random(n) < missing_rate
        df.loc[mask, c] = np.nan

    # Inject a few "hard outliers" to simulate bad ingestion/sensor glitches
    outlier_idx = rng.choice(n, size=max(6, n // 400), replace=False)
    df.loc[outlier_idx[: len(outlier_idx)//2], "sensor_temp_c"] = 200  # impossible
    df.loc[outlier_idx[len(outlier_idx)//2 :], "voltage_v"] = -5       # impossible

    return df


# ---------------------------
# Demo 1: Data validation (Chapter 8: data quality & governance)
# ---------------------------

def demo01_validation(df: pd.DataFrame, out_dir: Path, narrator: Narrator) -> List[Path]:
    narrator.section("Demo 1 — Data Validation as Decision Insurance (Quality Gate)")

    narrator.decision_box(DecisionBox(
        who_decides="Reliability Engineer / Ops Lead",
        decision="Can we trust this batch of telemetry enough to trigger alerts or maintenance actions?",
        risk_if_wrong="False alarms (wasted downtime) or missed failures (unsafe operation).",
        how_this_demo_helps="Creates an explicit quality gate that turns raw data into trusted information."
    ))

    narrator.text_block("Decision Context",
        "A monitoring system ingests telemetry continuously. If bad values slip through (e.g., impossible voltage),\n"
        "downstream analytics and alerting become unreliable. This demo shows how validation rules catch issues early\n"
        "and produce an actionable report instead of silently corrupting the pipeline."
    )

    narrator.text_block("Informatics Role",
        "Informatics converts **raw data → validated information**.\n"
        "Validation is a governance mechanism: it enforces schema + constraints so decisions are based on credible inputs."
    )

    artifacts: List[Path] = []

    # Minimal fallback if pandera isn't present
    if not PANDERA_AVAILABLE:
        # Simple rule checks (still teachable)
        checks = {
            "sensor_temp_c": lambda s: s.between(-20, 120) | s.isna(),
            "voltage_v": lambda s: s.between(0, 60) | s.isna(),
            "vibration_mm_s": lambda s: (s >= 0) | s.isna(),
            "pressure_kpa": lambda s: s.between(0, 600) | s.isna(),
            "load_pct": lambda s: s.between(0, 100) | s.isna(),
        }

        report_rows = []
        for col, fn in checks.items():
            ok = fn(df[col])
            bad_count = int((~ok).sum())
            report_rows.append({
                "column": col,
                "bad_count": bad_count,
                "bad_pct": float(bad_count / len(df)),
            })

        report = pd.DataFrame(report_rows).sort_values("bad_count", ascending=False)
        report_path = out_dir / "demo01_validation_report.csv"
        report.to_csv(report_path, index=False)
        artifacts.append(report_path)

        summary = {
            "pandera_available": False,
            "rows": int(len(df)),
            "invalid_cells_total": int(report["bad_count"].sum()),
            "invalid_by_column": report.set_index("column")["bad_count"].to_dict(),
            "action_recommendation": "Quarantine batch or route to remediation if invalid_cells_total > 0."
        }
        summary_path = out_dir / "demo01_validation_summary.json"
        write_json(summary_path, summary)
        artifacts.append(summary_path)

        narrator.text_block("Output (What you should notice)",
            f"- Saved a validation report to `{report_path.name}`\n"
            f"- Saved a validation summary to `{summary_path.name}`\n"
            "Even without Pandera, we produced a consistent, auditable quality gate."
        )

    else:
        schema = DataFrameSchema({
            "time_min": Column(int, Check.ge(0)),
            "load_pct": Column(float, [Check.ge(0), Check.le(100)], nullable=True),
            "sensor_temp_c": Column(float, [Check.ge(-20), Check.le(120)], nullable=True),
            "vibration_mm_s": Column(float, [Check.ge(0), Check.le(50)], nullable=True),
            "voltage_v": Column(float, [Check.ge(0), Check.le(60)], nullable=True),
            "pressure_kpa": Column(float, [Check.ge(0), Check.le(600)], nullable=True),
            "failure_within_24h": Column(int, Check.isin([0, 1])),
        })

        try:
            schema.validate(df, lazy=True)
            # If this passes, no issues (unlikely with injected outliers)
            report = pd.DataFrame([{"column": "ALL", "bad_count": 0, "bad_pct": 0.0}])
            invalid_total = 0
            invalid_by_column = {}
        except Exception as e:
            # Pandera's failure cases can be rich; we want a student-friendly report.
            # We extract "failure_cases" if present.
            failure_cases = getattr(e, "failure_cases", None)
            if failure_cases is None:
                # Generic error fallback
                failure_cases = pd.DataFrame({"column": ["unknown"], "failure_case": [str(e)]})

            # Normalize
            if "column" not in failure_cases.columns:
                failure_cases["column"] = "unknown"

            report = (failure_cases.groupby("column")
                      .size()
                      .reset_index(name="bad_count")
                      .sort_values("bad_count", ascending=False))
            report["bad_pct"] = report["bad_count"] / len(df)

            invalid_total = int(report["bad_count"].sum())
            invalid_by_column = report.set_index("column")["bad_count"].to_dict()

        report_path = out_dir / "demo01_validation_report.csv"
        report.to_csv(report_path, index=False)
        artifacts.append(report_path)

        summary = {
            "pandera_available": True,
            "rows": int(len(df)),
            "invalid_cells_total": invalid_total,
            "invalid_by_column": invalid_by_column,
            "action_recommendation": "If invalid_cells_total > 0: quarantine batch, remediate source, re-run validation."
        }
        summary_path = out_dir / "demo01_validation_summary.json"
        write_json(summary_path, summary)
        artifacts.append(summary_path)

        narrator.text_block("Output (What you should notice)",
            f"- Validation found **{invalid_total}** invalid cells (injected outliers simulate real ingestion glitches).\n"
            f"- Report: `{report_path.name}` (which columns failed and how often)\n"
            f"- Summary: `{summary_path.name}` (auditable decision support)\n"
            "This is what it looks like to treat data quality as part of the decision pipeline."
        )

    narrator.text_block("Interpretation",
        "When validation flags impossible readings, it usually indicates one of:\n"
        "- sensor faults\n"
        "- ingestion/parsing errors (units, sign, decimal shift)\n"
        "- schema drift\n\n"
        "The key informatics principle: **don’t let bad data quietly become ‘facts’**."
    )

    narrator.text_block("Decision Impact",
        "With an explicit quality gate, teams can quarantine the batch, remediate upstream issues, and reprocess.\n"
        "Without it, downstream models learn from corrupted inputs, which produces confident but wrong decisions."
    )

    narrator.artifacts(artifacts)
    return artifacts


# ---------------------------
# Demo 2: Missingness + imputation (Chapter 8: data completeness & uncertainty)
# ---------------------------

def demo02_missingness_imputation(df: pd.DataFrame, out_dir: Path, narrator: Narrator, show_plots: bool) -> List[Path]:
    narrator.section("Demo 2 — Missing Data: Filling Gaps Without Lying to Yourself")

    narrator.decision_box(DecisionBox(
        who_decides="Maintenance Planner / Data Analyst",
        decision="Do we have enough signal continuity to detect degradation trends and act?",
        risk_if_wrong="Hidden degradation (missed intervention) or overreaction to noisy estimates.",
        how_this_demo_helps="Quantifies missingness and shows imputation as a controlled approximation—plus uncertainty language."
    ))

    narrator.text_block("Decision Context",
        "Telemetry pipelines are messy: sensors drop packets, gateways reboot, networks hiccup.\n"
        "If you ignore missing data, you may erase a trend. If you impute blindly, you may manufacture certainty.\n"
        "This demo shows missingness profiling and a simple, transparent imputation approach."
    )

    narrator.text_block("Informatics Role",
        "Informatics is not just modeling—it’s **data stewardship**.\n"
        "Missingness is a first-class signal about system reliability and data pipeline health.\n"
        "Imputation converts partial data into a usable dataset, but must preserve the idea that it’s an estimate."
    )

    artifacts: List[Path] = []

    cols = ["load_pct", "sensor_temp_c", "vibration_mm_s", "voltage_v", "pressure_kpa"]
    missing_counts = df[cols].isna().sum().to_dict()
    missing_pct = (df[cols].isna().mean() * 100).round(2).to_dict()

    missing_summary = {
        "rows": int(len(df)),
        "missing_counts": {k: int(v) for k, v in missing_counts.items()},
        "missing_pct": {k: float(v) for k, v in missing_pct.items()},
        "note": "Imputation introduces estimates; downstream decisions should acknowledge uncertainty."
    }

    summary_path = out_dir / "demo02_missingness_summary.json"
    write_json(summary_path, missing_summary)
    artifacts.append(summary_path)

    narrator.text_block("Output (What you should notice)",
        f"- Missingness summary saved to `{summary_path.name}`\n"
        "Look for columns with high missingness: they can compromise trend detection and model stability."
    )

    # Impute using time-based interpolation (works since we have a time index)
    df_sorted = df.sort_values("time_min").reset_index(drop=True)
    imputed = df_sorted.copy()
    imputed[cols] = imputed[cols].interpolate(method="linear", limit_direction="both")

    # Compare one signal before/after
    signal = "sensor_temp_c"
    plot_path = out_dir / "demo02_imputation_plot.png"

    plt.figure()
    # plot raw (with gaps) as points, imputed as line
    plt.plot(df_sorted["time_min"], imputed[signal], label="Imputed (linear)")
    plt.scatter(df_sorted["time_min"], df_sorted[signal], s=6, label="Observed (gappy)")
    plt.xlabel("Time (min)")
    plt.ylabel(signal)
    plt.title("Missingness + Imputation: Observed vs Imputed")
    plt.legend()
    plt.tight_layout()
    plt.savefig(plot_path, dpi=160)
    artifacts.append(plot_path)

    if show_plots:
        plt.show()
    plt.close()

    narrator.text_block("Interpretation",
        "Interpolation restores continuity, which is useful for visualization and some models.\n"
        "But it can also smooth out real spikes. So the *right mental model* is:\n"
        "- observed points = evidence\n"
        "- imputed points = best guess\n\n"
        "In practice, you often track a companion indicator like `is_imputed` per cell/row."
    )

    narrator.text_block("Decision Impact",
        "You can now:\n"
        "- detect trends without breaking the timeline\n"
        "- run baseline models for early insight\n\n"
        "But you should avoid irreversible operational actions (e.g., shutdown) based solely on imputed segments.\n"
        "This is the informatics ethic: **use estimates, but label them honestly**."
    )

    narrator.artifacts(artifacts)
    return artifacts


# ---------------------------
# Demo 3: Synthetic data + simple model + interpretable outputs
# (Chapter 8: evaluation, risk, and decision thresholds)
# ---------------------------

def demo03_modeling(df: pd.DataFrame, out_dir: Path, narrator: Narrator, show_plots: bool) -> List[Path]:
    narrator.section("Demo 3 — From Data → Decision: A Minimal, Auditable Predictive Model")

    narrator.decision_box(DecisionBox(
        who_decides="Ops Lead / Reliability Team",
        decision="Should we schedule preventative maintenance in the next 24 hours?",
        risk_if_wrong="Unplanned failure (high cost) or unnecessary maintenance (downtime + waste).",
        how_this_demo_helps="Builds a small, interpretable model and reports metrics + confusion matrix as decision evidence."
    ))

    narrator.text_block("Decision Context",
        "Most real teams start with *something simple that works*.\n"
        "This demo trains a basic logistic regression model to predict `failure_within_24h` from telemetry features.\n"
        "We emphasize auditable evaluation outputs instead of chasing fancy modeling."
    )

    narrator.text_block("Informatics Role",
        "This is the classic pipeline:\n"
        "**data → features → model → evaluation → decision threshold → action**.\n"
        "Informatics asks: can we justify the model outputs as trustworthy inputs to decisions?"
    )

    artifacts: List[Path] = []

    # Prepare features
    feature_cols = ["load_pct", "sensor_temp_c", "vibration_mm_s", "voltage_v", "pressure_kpa"]
    model_df = df[feature_cols + ["failure_within_24h"]].copy()

    # Basic imputation (median) for modeling baseline; keep it explicit and honest
    medians = model_df[feature_cols].median(numeric_only=True)
    model_df[feature_cols] = model_df[feature_cols].fillna(medians)

    # Save dataset for students to inspect
    dataset_path = out_dir / "demo03_synthetic_dataset.csv"
    model_df.to_csv(dataset_path, index=False)
    artifacts.append(dataset_path)

    X = model_df[feature_cols].values
    y = model_df["failure_within_24h"].values

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.25, random_state=42, stratify=y
    )

    # Simple, interpretable baseline
    clf = LogisticRegression(max_iter=500)
    clf.fit(X_train, y_train)

    # Predictions
    y_prob = clf.predict_proba(X_test)[:, 1]
    # Default threshold = 0.5 (we will discuss thresholding as a decision policy)
    threshold = 0.5
    y_pred = (y_prob >= threshold).astype(int)

    # Metrics
    metrics = {
        "threshold": threshold,
        "accuracy": float(accuracy_score(y_test, y_pred)),
        "precision": float(precision_score(y_test, y_pred, zero_division=0)),
        "recall": float(recall_score(y_test, y_pred, zero_division=0)),
        "f1": float(f1_score(y_test, y_pred, zero_division=0)),
        "base_rate_failure": float(y_test.mean()),
        "note": "Metrics depend on decision threshold. In real systems, threshold is chosen based on cost of false positives/negatives."
    }
    metrics_path = out_dir / "demo03_model_metrics.json"
    write_json(metrics_path, metrics)
    artifacts.append(metrics_path)

    narrator.text_block("Output (What you should notice)",
        f"- Saved the modeling dataset to `{dataset_path.name}` (inspect it; understand the features)\n"
        f"- Saved model metrics to `{metrics_path.name}`\n"
        "These artifacts are designed to be *decision-facing evidence*, not just ML trivia."
    )

    # Confusion matrix plot
    cm = confusion_matrix(y_test, y_pred)
    cm_path = out_dir / "demo03_confusion_matrix.png"

    plt.figure()
    plt.imshow(cm, interpolation="nearest")
    plt.title("Confusion Matrix (Threshold = 0.5)")
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.colorbar()
    tick_marks = np.arange(2)
    plt.xticks(tick_marks, ["NoFail", "Fail"])
    plt.yticks(tick_marks, ["NoFail", "Fail"])

    # Annotate
    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            plt.text(j, i, str(cm[i, j]), ha="center", va="center")

    plt.tight_layout()
    plt.savefig(cm_path, dpi=160)
    artifacts.append(cm_path)
    if show_plots:
        plt.show()
    plt.close()

    # Feature importance (logistic regression coefficients as a simple interpretability tool)
    coefs = clf.coef_.ravel()
    coef_df = pd.DataFrame({"feature": feature_cols, "coef": coefs}).sort_values("coef", ascending=False)

    fi_path = out_dir / "demo03_feature_importance.png"
    plt.figure()
    plt.bar(coef_df["feature"], coef_df["coef"])
    plt.xticks(rotation=30, ha="right")
    plt.ylabel("Coefficient (log-odds contribution)")
    plt.title("Interpretability: Logistic Regression Coefficients")
    plt.tight_layout()
    plt.savefig(fi_path, dpi=160)
    artifacts.append(fi_path)
    if show_plots:
        plt.show()
    plt.close()

    # Plain-English interpretation text
    top_pos = coef_df.iloc[0]
    top_neg = coef_df.iloc[-1]

    narrator.text_block("Interpretation",
        "The confusion matrix tells a story:\n"
        "- **False negatives** (missed failures) are the scary ones if safety is critical.\n"
        "- **False positives** (unnecessary maintenance) are costly but usually safer.\n\n"
        "The coefficient chart is a simple interpretability tool:\n"
        f"- Most positive driver (in this fit): `{top_pos['feature']}`\n"
        f"- Most negative driver (in this fit): `{top_neg['feature']}`\n\n"
        "Important: coefficients are not 'truth'—they’re a transparent summary of what this model learned from this dataset."
    )

    narrator.text_block("Decision Impact",
        "You now have a defensible baseline model and evaluation evidence.\n"
        "Next step (policy): choose a threshold based on cost.\n"
        "- If missed failures are unacceptable → lower threshold to increase recall.\n"
        "- If maintenance is extremely expensive → raise threshold to increase precision.\n\n"
        "That’s Chapter 8 in action: evaluation is not academic—it defines operational decision policy."
    )

    narrator.artifacts(artifacts)
    return artifacts


# ---------------------------
# Main
# ---------------------------

def parse_args(argv: Optional[List[str]] = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Lecture 03 explainable demos (Chapter 8 + Informatics linkages).")
    p.add_argument("--out_dir", type=str, default="artifacts", help="Output directory for artifacts.")
    p.add_argument("--show_plots", type=int, default=0, help="1 to display plots; 0 to only save PNGs.")
    p.add_argument("--n_rows", type=int, default=2500, help="Number of synthetic rows to generate.")
    p.add_argument("--missing_rate", type=float, default=0.08, help="Missingness rate for synthetic data.")
    p.add_argument("--seed", type=int, default=42, help="Random seed.")
    return p.parse_args(argv)


def main(argv: Optional[List[str]] = None) -> int:
    args = parse_args(argv)
    out_dir = Path(args.out_dir)
    safe_mkdir(out_dir)

    show_plots = bool(args.show_plots)

    narrator = Narrator(out_dir=out_dir)

    # Generate dataset once for all demos
    df = generate_telemetry_dataset(
        n=args.n_rows,
        missing_rate=args.missing_rate,
        seed=args.seed,
    )

    # Run demos
    _ = demo01_validation(df, out_dir, narrator)
    _ = demo02_missingness_imputation(df, out_dir, narrator, show_plots=show_plots)
    _ = demo03_modeling(df, out_dir, narrator, show_plots=show_plots)

    # Finalize narrative markdown
    md_path = narrator.finalize()

    print("\n" + "-" * 88)
    print("DONE")
    print(f"Artifacts written to: {out_dir.resolve()}")
    print(f"Demo narrative markdown: {md_path.resolve()}")
    print("-" * 88)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
